package AbyssEngine;

public final class GameRecord {
   public boolean[] var_df = new boolean[100];
   public int credits;
   public int rating;
   public long playTime;
   public int kills;
   public int missionCount;
   public int level;
   public int lastWorth;
   public int var_4b1;
   public int var_4d6;
   public int var_552;
   public int var_5ee;
   public int var_663;
   public int stationsVisited;
   public int var_73b;
   public int var_81e;
   public int var_883;
   public int var_8e6;
   public int var_97f;
   public Mission var_9a3;
   public Mission var_a05;
   public Station[] var_a51;
   public int[] var_a68;
   public boolean[] var_a74 = new boolean[11];
   public boolean[] var_ad5 = new boolean[11];
   public int var_b28;
   public int var_b4b;
   public int var_b83;
   public int var_bce;
   public boolean[] var_c0d = new boolean[22];
   public int var_c47;
   public boolean[] var_c81 = new boolean[22];
   public int var_cbe;
   public long var_cfa;
   public int var_d55;
   public int var_d83;
   public int var_dcf;
   public int var_de1;
   public int var_e29;
   public int var_e62;
   public int var_e81;
   public int var_e95;
   public int var_ea3;
   public int var_ede;
   public boolean var_f30 = false;
   public boolean var_f50 = false;
   public boolean var_f5f = false;
   public boolean var_f6c = false;
   public boolean var_fc2 = false;
   public boolean var_100f = false;
   public boolean var_1038 = false;
   public boolean var_1047 = false;
   public boolean var_108f = false;
   public boolean var_10ed = false;
   public boolean var_119d = false;
   public boolean var_11c5 = false;
   public boolean var_11eb = false;
   public boolean var_121f = false;
   public boolean var_1273 = false;
   public boolean var_12c6 = false;
   public boolean var_12e2 = false;
   public boolean var_132f = false;
   public boolean var_1378 = false;
   public boolean var_1392 = false;
   public boolean var_13ae = false;
   public boolean var_13db = false;
   public boolean var_13f8 = false;
   public boolean var_1407 = false;
   public boolean var_1428 = false;
   public boolean var_1449 = false;
   public boolean var_1459 = false;
   public long var_148e = 0L;
   public long var_14c1 = 0L;
   public Ship var_14f4;
   public Station var_1521;
   public Standing var_1566;
   public BluePrint[] var_157c;
   public ProducedGood[] var_15d9;
   public Agent[] var_162f;
   public String[] var_1646;
   public int var_1685;
   public int var_16d5;
   public byte[] var_1721;
   public int var_175b;
   public boolean[] var_17bb;
   public int[] var_17e0;
   public int[] var_1829;
   public byte[] var_186b;
   public byte[] var_187b;
   public String stationName;

   public final String toString() {
      return "Playing time: \t\t" + Time.timeToHMS(this.playTime) + "\n" + "Level: \t\t" + this.level + "\n" + "Credits: \t\t" + this.credits + "\n\n" + "Rating: \t\t" + this.rating + "\n" + "Kills: \t\t" + this.kills + "\n" + "MissionCount: \t\t" + this.missionCount + "\n" + "LastWorth: \t\t" + this.lastWorth + "\n" + "StationsVisited: \t\t" + this.stationsVisited + "\n";
   }
}
