package GoF2;

import AE.Time;

public final class GameRecord {
   public boolean[] visitedStations = new boolean[100];
   public int credits;
   public int rating;
   public long playTime;
   public int kills;
   public int missionCount;
   public int level;
   public int lastWorth;
   public int goodsProduced;
   public int pirateKills;
   public int jumpGateUses;
   public int cargoSalvaged;
   public int unused__;
   public int stationsVisited;
   public int currentCampaignMissionIndex;
   public int wormholeStation;
   public int wormholeSystem;
   public int lastVisitedNonVoidOrbit;
   public int wormHoleTick;
   public Mission freelanceMission;
   public Mission storyMission;
   public Station[] lastVisitedStations;
   public int[] achievements;
   public boolean[] minedOreTypes = new boolean[11];
   public boolean[] minedCoreTypes = new boolean[11];
   public int missionGoodsCarried;
   public int minedOre;
   public int minedCores;
   public int boughtBooze;
   public boolean[] drinkTypesPossesed = new boolean[22];
   public int destroyedJunk;
   public boolean[] systemsVisited = new boolean[22];
   public int passengersCarried;
   public long invisibleTime;
   public int bombsUsed;
   public int alienJunkSalvaged;
   public int barInteractions;
   public int commandedWingmen;
   public int asteroidsDestroyed;
   public int maxFreeCargo;
   public int missionsRejected;
   public int askedToRepeate;
   public int acceptedNotAskingDifficulty;
   public int acceptedNotAskingLocation;
   public boolean shopHelpShown = false;
   public boolean shipHelpShown = false;
   public boolean actionsHelpShown = false;
   public boolean bluePrintsHelpShown = false;
   public boolean bluePrintInfoHelpShown = false;
   public boolean barHelpShown = false;
   public boolean galaxyMapHelpShown = false;
   public boolean systemMapHelpShown = false;
   public boolean unused12121_ = false;
   public boolean miningHelpShown = false;
   public boolean asteroidHelpShown = false;
   public boolean missionsHelpShown = false;
   public boolean cargoFullHelpShown = false;
   public boolean wingmenHelpShown = false;
   public boolean actionMenuHelpShown = false;
   public boolean boosterHelpShown = false;
   public boolean statusHelpShown = false;
   public boolean medalsHelpShown = false;
   public boolean fanWingmenNoticeShown = false;
   public boolean voidxNoticeShown = false;
   public boolean reputationHelpShown = false;
   public boolean buyingHelpShown = false;
   public boolean itemMountingHelpShown = false;
   public boolean itemMounting2HelpShown = false;
   public boolean interplanetHelpShown = false;
   public boolean jumpDriveHelpShown = false;
   public boolean cloakHelpShown = false;
   public long loadingsCount = 0L;
   public long timeSpentLoading = 0L;
   public Ship egoShip;
   public Station currentStation;
   public Standing standing;
   public BluePrint[] blueprints;
   public ProducedGood[] waitingGoods;
   public Agent[] specialAgents;
   public String[] wingmenNames;
   public int wingmanRace;
   public int wingmenTimeRemaining;
   public byte[] wingmanFace;
   public int passengerCount;
   public boolean[] visibleSystems;
   public int[] lowestItemPrices;
   public int[] highestItemPrices;
   public byte[] lowestItemPriceSystems;
   public byte[] highestItemPriceSystems;
   public String stationName;

   public final String toString() {
      return "Playing time: \t\t" + Time.timeToHMS(this.playTime) + "\n" + "Level: \t\t" + this.level + "\n" + "Credits: \t\t" + this.credits + "\n\n" + "Rating: \t\t" + this.rating + "\n" + "Kills: \t\t" + this.kills + "\n" + "MissionCount: \t\t" + this.missionCount + "\n" + "LastWorth: \t\t" + this.lastWorth + "\n" + "StationsVisited: \t\t" + this.stationsVisited + "\n";
   }
}
